# Generated by Django 6.0.2 on 2026-02-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube video URL for the course', max_length=500, null=True),
        ),
    ]
